Repository LIKELION-FE-LAB9/Market-Karly, pull requests merged in 2023-02, with the labels that each got.

#100 [#46, #47, #48, #49] Login Markup 완성
  client/html/login.html
Labels: ❤️ Feature

#129 [#128 #127 #125 #119 #120 #119 #116 #115 #105] Product-List Main, Footer CSS 완성 및 코드 리팩토링
  client/assets/icons/Icon/Arrow.svg
  client/assets/icons/Icon/Frame.svg
  client/assets/icons/Icon/Vector.svg
  client/assets/icons/Icon/arrow-down.svg
  client/assets/icons/Icon/arrow-up.svg
  client/assets/icons/Icon/btn-back.svg
  client/assets/icons/Icon/btn-first.svg
  client/assets/icons/Icon/btn-front.svg
  client/assets/icons/Icon/btn-last.svg
  client/css/base/base.css
  client/css/components/footer.css
  client/css/pages/product-list.css
  client/html/product-list.html
Labels: ❤️ Feature, 🔴 Priority: Critical

#126 [#99] product-detail_main CSS 완성
  client/assets/icons/Icon/btn-minus.svg
  client/assets/icons/Icon/btn-plus.svg
  client/assets/icons/Icon/lock.svg
  client/assets/icons/Icon/product_01.svg
  client/assets/spicy-chewy-noodles/detail-info.png
  client/assets/spicy-chewy-noodles/product.png
  client/assets/spicy-chewy-noodles/thumbnail.png
  client/css/pages/product-detail.css
  client/html/product-detail.html
Labels: ❤️ Feature

#130 [#109, #110, #111] Login CSS 완성 및 html 리팩토링, Cart CSS완성 및 html 리팩토링
  client/assets/icons/Icon/Frozen.svg
  client/assets/icons/Icon/Refrigerated.svg
  client/assets/icons/Icon/check-off.svg
  client/assets/icons/Icon/check-on.svg
  client/assets/icons/Icon/icon_down2.svg
  client/assets/icons/Icon/sunny.svg
  client/css/pages/cart.css
  client/css/pages/login.css
  client/html/cart.html
  client/html/login.html
Labels: ❤️ Feature

#135 [#99] product-detail main CSS 너비 수정
  client/assets/icons/Icon/lock.svg
  client/assets/icons/Icon/review-notice.svg
  client/css/pages/product-detail.css
  client/html/product-detail.html
Labels: 🔨 Refactor

#136 [#25, #102, #106, #104, #107, #28, #30, #108, #112, #78, #113, #88, #117, #118, #51, #55] Header, main CSS 완성 및 리팩토링, swiper js 작업 추가
  client/assets/icons/Icon/Cart-round.svg
  client/assets/icons/Icon/Direction_Down.svg
  client/assets/icons/Icon/Direction_Up.svg
  client/assets/icons/Icon/MenuIcon.svg
  client/assets/icons/Icon/MenuIcon_p.svg
  client/assets/icons/Icon/arrow_w.svg
  client/assets/icons/Icon/count_minus_off.svg
  client/assets/icons/Icon/count_minus_on.svg
  client/assets/icons/Icon/count_plus_off.svg
  client/assets/icons/Icon/count_plus_on.svg
  client/assets/icons/Icon/icon_down.svg
  client/css/components/header.css
  client/css/pages/main.css
  client/html/main.html
  client/js/main/mkk.js
  client/js/main/mkk_swiper.js
Labels: ❤️ Feature

#137 [#92, #122, #123, #124] 회원가입_회원정보 입력, 개인정보 입력, 선택사항, 이용약관
  client/css/pages/register.css
  client/html/register.html
Labels: ❤️ Feature

#139 [#99] product-detail html, css 화면 깨짐 수정
  client/css/pages/product-detail.css
  client/html/product-detail.html
Labels: 🔨 Refactor

#141 Cart Main CSS 리팩토링
  client/css/pages/cart.css
Labels: 🔨 Refactor

#142 [#109] login 리팩토링
  client/css/pages/login.css
  client/html/login.html
Labels: 🔨 Refactor

#149 [#148] Product-List | Navigator 구현
  client/css/pages/product-list.css
  client/html/product-list.html
  client/js/product_list/ukss.js
Labels: ❤️ Feature, 🥤 Request, 🟠 Priority: High

#153 [#56] 상품 선택 수량 버튼 누르면 수량만큼 총 금액 표시 기능
  client/assets/icons/Icon/product-detail-first.svg
  client/css/pages/product-detail.css
  client/html/product-detail.html
  client/js/product_detail/seohyun.js
Labels: ❤️ Feature

#155 [#152, #154] Product-List | group 구현
  client/css/pages/product-list.css
  client/html/product-list.html
  client/js/product_list/ukss.js
Labels: ❤️ Feature, 🥤 Request, 🔨 Refactor, 🟠 Priority: High

#159 [#86, #45, #50, #80, #103, #157 ] Top Banner 및 Header CSS 수정 및 JS 추가
  client/assets/icons/Icon/Hamburger-p.svg
  client/assets/icons/Icon/cover.svg
  client/assets/icons/Icon/logo_wooriBank.svg
  client/css/components/header.css
  client/css/pages/main.css
  client/html/main.html
  client/js/common/common.js
  client/js/main/mkk.js
Labels: ❤️ Feature, 🥤 Request, 🟠 Priority: High

#160 [#147] 로그인 버튼 클릭 시 팝업 창 구현
  client/css/pages/login.css
  client/html/login-popup.html
  client/html/login.html
  client/js/login/jm.js
Labels: ❤️ Feature

#161 [#59] 하트 아이콘 누르면 색이 변하는 기능
  client/assets/icons/Icon/squre-empty-heart.svg
  client/html/product-detail.html
  client/js/product_detail/seohyun.js
Labels: ❤️ Feature

#162 [#67] 장바구니 담기 버튼 누르면 제품 정보 보여주고 사라지는 기능
  client/assets/icons/Icon/cart-polygon.svg
  client/css/pages/product-detail.css
  client/html/product-detail.html
  client/js/product_detail/seohyun.js
Labels: ❤️ Feature

#164 [#163] Product-List | data 파싱 출력
  client/assets/icons/Icon/Minus.svg
  client/assets/icons/Icon/Plus.svg
  client/css/pages/product-list.css
  client/html/product-list.html
  client/js/product_list/ukss.js
  server/db/data.json
Labels: ❤️ Feature, 🥤 Request, 🔨 Refactor, 🔴 Priority: Critical

#166 [#131] Cart 화살표 클릭 시 장바구니 목록 생성
  client/assets/icons/Icon/up.svg
  client/assets/icons/Icon/x.svg
  client/css/pages/cart.css
  client/html/cart.html
  client/js/cart/jm.js
Labels: ❤️ Feature

#167 [#163] Product-List | data 추가
  client/assets/brooklyn/thumbnail.jpg
  client/assets/dongmulbokji/thumbnail.jpg
  client/assets/envyapple/thumbnail.jpg
  client/assets/galbitang/thumbnail.jpg
  client/assets/haenamrice/thumbnail.jpg
  client/assets/handon/thumbnail.jpg
  client/assets/mokran/thumbnail.jpg
  client/assets/muhangsaengje/thumbnail.jpg
  client/assets/sobulgogi/thumbnail.jpg
  client/assets/strawberry/thumbnail.jpg
  client/assets/thumbnail.png
  client/assets/todaysalad/thumbnail.jpg
  client/assets/yangnyeom/thumbnail.jpg
  client/css/pages/product-list.css
  client/js/product_list/ukss.js
  server/db/data.json
Labels: ❤️ Feature, 🥤 Request, 🟢 Priority: Low

#168 [#26, #104, #103, #75, #107, #64, #117] Header, Main banner 리팩토링 및 Header, Top banner, popup, addcart JS 추가
  client/assets/banner/banner01.png
  client/assets/icons/Icon/search-b.svg
  client/css/components/header.css
  client/css/pages/main.css
  client/html/main.html
  client/js/common/common.js
  client/js/main/mkk.js
  client/js/main/mkk_swiper.js
Labels: 🐞 BugFix, ❤️ Feature

#170 [#68] 상품 디테일 밑에 있는 메뉴 클릭 시 의미에 맞는 페이지가 보이는 기능
  client/js/product_detail/seohyun.js
Labels: ❤️ Feature

#169 [#57, #58] 회원가입_이메일 인증 버튼 구현, 회원가입_비밀번호, 비밀번호 확인
  client/css/pages/register.css
  client/html/register.html
  client/js/register/woonki.js
Labels: ❤️ Feature

#171 [#63] 회원가입 버튼 기능 추가
  client/html/register.html
  client/js/register/woonki.js
Labels: ❤️ Feature

#174 [#104] header - member 요소 CSS 리팩토링
  client/css/components/header.css
Labels: 🐞 BugFix

#175 [feat] ID, PW 로컬스토리지에 보내기
  client/css/pages/register.css
  client/html/register.html
  client/js/register/woonki.js
Labels: ❤️ Feature

#176 [#69] 후기 작성하기 누르면 팝업 창 띄우는 기능 구현 중
  client/css/pages/product-detail.css
  client/html/product-detail.html
  client/js/product_detail/seohyun.js
Labels: ❤️ Feature

#178 [#156, #172] Product-List | 모달창 제작 및 최종 완성
  client/css/components/header.css
  client/css/pages/product-list.css
  client/html/product-list.html
  client/js/product_list/ukss.js
Labels: ❤️ Feature, 🥤 Request, 🔴 Priority: Critical

#177 [#143] +- 버튼 클릭 시 숫자 증가
  client/css/pages/cart.css
  client/html/cart.html
  client/js/cart/jm.js
  client/js/login/jm.js
Labels: ❤️ Feature, 🔨 Refactor

#179 [#75] POPUP AD 오늘하루 안 보기 기능 구현
  client/css/pages/main.css
  client/js/main/mkk.js
Labels: ❤️ Feature

#181 [#45, #118, #180, #79, #103] Top banner 닫기, Go to Top 버튼, recent product - JS 기능 구현
  client/css/components/header.css
  client/css/pages/main.css
  client/html/main.html
  client/js/common/common.js
  client/js/main/mkk.js
Labels: 🐞 BugFix, ❤️ Feature

#183 [#182] 가입하기 버튼, 서버연동
  client/html/register.html
  client/js/register/woonki.js
Labels: ❤️ Feature

#185 [#69, #73] 후기 팝업, 문의 팝업 기능 추가
  client/assets/icons/Icon/detail-popup-cancel.svg
  client/css/pages/product-detail.css
  client/html/product-detail.html
  client/js/product_detail/seohyun.js
  client/lib/dom/css.js
Labels: 🐞 BugFix, ❤️ Feature

#187 [#103, #186] 추천 상품 리스트 data.json 적용
  client/css/components/header.css
  client/css/pages/main.css
  client/html/main.html
  client/js/common/common.js
  client/js/main/mkk.js
Labels: ❤️ Feature
